### ISSUE TITLE
edit validator nil pointer 

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/go-sdk#69]
```
./hmy --node=https://api.s0.pga.hmny.io/ staking edit-validator --validator-addr one1hs80ss7xzxt6rl6kkvecc4yrenttx8dw308vyj --name Mirror --identity Mirror --website mirrormirage0@gmail.com --security-contact Mirror --details "One Too Many"  --rate 0.01 --min-self-delegation 2 --max-total-delegation 30 --remove-bls-key 4cc25d3c530d8ce6d0ec3c1e8f14454739fbf69b607cd80e2567252ac7d426f85f2cffebf47b2f6b28031d5bfd70b815 --add-bls-key 4cc25d3c530d8ce6d0ec3c1e8f14454739fbf69b607cd80e2567252ac7d426f85f2cffebf47b2f6b28031d5bfd70b815 --chain-id pangaea
Enter the bls passphrase:
Repeat the bls passphrase:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0e903]

goroutine 1 [running]:
github.com/harmony-one/go-sdk/cmd/subcommands.delegationAmountSanityCheck(0xc0002cc120, 0xc0002cc140, 0x0, 0x0, 0x0)
    /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/staking.go:167 +0x143
github.com/harmony-one/go-sdk/cmd/subcommands.stakingSubCommands.func2(0xc0002f9400, 0xc0000afa00, 0x0, 0x19, 0x0, 0x0)
    /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/staking.go:412 +0x3a3
github.com/spf13/cobra.(*Command).execute(0xc0002f9400, 0xc0000af860, 0x19, 0x1a, 0xc0002f9400, 0xc0000af860)
    /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x15a3d80, 0x10, 0x0, 0xc000306280)
    /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
    /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/harmony-one/go-sdk/cmd/subcommands.Execute()
    /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/root.go:87 +0x2e
main.main()
    /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/main.go:37 +0xec
```

**Comment by fxfactorial** [comment]
https://github.com/harmony-one/harmony/issues/1961
